
language: java

jdk:
  - openjdk17

addons:
  sonarcloud:
    organization: "phantrang-phan"
    token:
      secure: "$SONAR_TOKEN"

git:
  depth: false

script:
  - mkdir -p bin
  - javac -cp "src/gson-2.10.1.jar" -d bin src/*.java
  - echo "Biên dịch thành công!"
  # Kiểm tra xem token đã được truyền chưa
  - echo "Starting SonarCloud analysis..."
  - sonar-scanner -Dsonar.login=$SONAR_TOKEN
    # (Tùy chọn) Nếu muốn kiểm tra biên dịch
