language: java

jdk:
  - openjdk17

addons:
  sonarcloud:
    organization: "phantrang-phan"
    token:
      secure: "$SONAR_TOKEN"

git:
  depth: false

script:
  # SonarCloud phân tích mã nguồn trong thư mục src
  - sonar-scanner
  
  # (Tùy chọn) Nếu muốn kiểm tra biên dịch
  - mkdir -p bin
  - javac -cp "src/gson-2.10.1.jar" -d bin src/*.java
  - echo "Biên dịch thành công!"